### ISSUE TITLE
Unexpected EOF on security policy apply

### ISSUE THREAD

**Issue by pryorda** [terraform-providers/terraform-provider-panos#153]
With Terraform v0.11.11 and pan provider 1.5.1 I'm seeing connection is shut down when applying a large set of security policies with rules.

``` 
2019/03/23 00:05:54 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [connection is shut down]
2019/03/23 00:05:54 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [connection is shut down]
2019/03/23 00:05:54 [TRACE] [walkApply] Exiting eval tree: panos_security_policy.VPN_to_QA_DMZ
2019/03/23 00:05:54 [TRACE] root: eval: *terraform.EvalGetProvider
2019/03/23 00:05:54 [TRACE] root: eval: *terraform.EvalReadState
2019/03/23 00:05:54 [TRACE] root: eval: *terraform.EvalValidateResource
2019/03/23 00:05:54 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [connection is shut down]
2019/03/23 00:05:54 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [connection is shut down]
2019/03/23 00:05:54 [TRACE] [walkApply] Exiting eval tree: panos_security_policy.QA_DMZ_to_QA
```

I've tried adding logging = ['action', 'send', 'receive' ] to see whats going on, but I don't know the location of the logs. 

Let me know how I can help diagnose this issue.

Thanks

**Comment by pryorda** [comment]
[Gist](https://gist.github.com/pryorda/63502d387639324ae20e6a42f5b2d4db)

**Comment by pryorda** [comment]
Narrowed it down to this error. 

``` 
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: panic: interface conversion: interface {} is nil, not string
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: 
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: goroutine 8146 [running]:
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: github.com/terraform-providers/terraform-provider-panos/panos.asStringList(0xc000978340, 0x1, 0x1, 0x15, 0xc0000da218, 0x1)
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-panos/panos/util.go:101 +0x110
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: github.com/terraform-providers/terraform-provider-panos/panos.parseSecurityPolicy(0xc0001a2230, 0x1d15600, 0xc0000a59b8, 0x100bf68, 0x70, 0x1c9db20, 0x1, 0xc0001a2230)
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-panos/panos/resource_security_policy.go:265 +0x714
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: github.com/terraform-providers/terraform-provider-panos/panos.createUpdateSecurityPolicy(0xc0001a2230, 0x1cc3680, 0xc0006943c0, 0xc0001a2230, 0x0)
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-panos/panos/resource_security_policy.go:297 +0x47
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: github.com/terraform-providers/terraform-provider-panos/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000324000, 0xc00063c780, 0xc00000a400, 0x1cc3680, 0xc0006943c0, 0x100b601, 0xc0000a5b80, 0x10bdc4c)
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-panos/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x351
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: github.com/terraform-providers/terraform-provider-panos/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0003248c0, 0xc00063c730, 0xc00063c780, 0xc00000a400, 0xc000392400, 0xc0000a5b48, 0x2a57880)
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-panos/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0x9c
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: github.com/terraform-providers/terraform-provider-panos/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc0006f12a0, 0xc00000a0e0, 0xc0009780f0, 0x0, 0x0)
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-panos/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: reflect.Value.call(0xc000084900, 0xc0002eac68, 0x13, 0x1ccea78, 0x4, 0xc0000a5f18, 0x3, 0x3, 0xc0002f2240, 0xc0006a6700, ...)
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: 	/opt/goenv/versions/1.11.4/src/reflect/value.go:447 +0x454
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: reflect.Value.Call(0xc000084900, 0xc0002eac68, 0x13, 0xc000368f18, 0x3, 0x3, 0x0, 0xc000368f28, 0x1000000000001)
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: 	/opt/goenv/versions/1.11.4/src/reflect/value.go:308 +0xa4
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: net/rpc.(*service).call(0xc0003cd280, 0xc00034ebe0, 0xc000574ec0, 0xc000574ed0, 0xc000342b00, 0xc0004b5220, 0x1b000e0, 0xc00000a0e0, 0x16, 0x1b00120, ...)
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: 	/opt/goenv/versions/1.11.4/src/net/rpc/server.go:384 +0x14e
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: created by net/rpc.(*Server).ServeCodec
2019-03-25T13:34:00.308-0600 [DEBUG] plugin.terraform-provider-panos_v1.5.1_x4: 	/opt/goenv/versions/1.11.4/src/net/rpc/server.go:481 +0x47e
 ```

**Comment by shinmog** [comment]
@pryorda 

This is complaining about the `destination_addresses` value of one of your security rules.  The `destination_addresses` param is expecting a list of strings, but it seems that one of the values is a nil instead of a string...?

Can you look over your various `destination_addresses` settings and see if anything looks weird?

**Comment by pryorda** [comment]
Yep, I limited it to that and fixed the issue with my sonicwall to hcl converter.

What do you think about updating: https://github.com/terraform-providers/terraform-provider-panos/blob/master/panos/resource_security_policy.go#L254 to check to make sure its not nil rather then panicing?

**Comment by shinmog** [comment]
Can you share what the setting was that caused this?

**Comment by pryorda** [comment]
```    rule {
    name                  = "${panos_address_group.QAEX_EXT_KONG.name} to ${panos_address_group.QA_PSQLDB_SERVERS.name} allow 914e74bd"
    source_zones          = ["${panos_zone.QA_DMZ.name}"]
    source_addresses      = ["${panos_address_group.QAEX_EXT_KONG.name}"]
    source_users          = ["any"]
    hip_profiles          = ["any"]
    destination_zones     = ["${panos_zone.QA.name}"]
    destination_addresses = [""]
    applications          = ["any"]
    services              = ["${panos_service_object.TCP_5432.name}"]
    categories            = ["any"]
    action                = "allow"
    description           = "No Comment!: ${panos_address_group.QAEX_EXT_KONG.name} to ${panos_address_group.QA_PSQLDB_SERVERS.name} allow 914e74bd"
    tags                  = ["${panos_administrative_tag.QA_DMZ.name}", "${panos_administrative_tag.QA.name}", "${panos_administrative_tag.MIGRATED.name}"]
  }  ```

**Comment by shinmog** [comment]
A list with an empty string..?  This feels like a breech of the guarantees that Terraform is supposed to have in place, specifically with regards to strings.

Let me reach out to HashiCorp and see what they have to say.

**Comment by pryorda** [comment]
I've looked in other places and it looks like they mainly handle the error gracefully and print it or print the error from the api.

**Comment by pryorda** [comment]
I've got it to work now that I removed all the null data

**Comment by shinmog** [comment]
I'm thinking I might end up having to fix this provider side.  I am still waiting on confirmation one way or the other from HashiCorp, but it's strange that the empty value for a string is the empty string, but yet the empty value for a slice of strings is `nil`.  This really feels like a HCL bug, but it does have implications for the provider, so I should fix it...
